const fs = require('fs')

fs.writeFileSync('src/lib/utils.js', [
"import { addDays, addMonths, format, parseISO, isBefore, isToday } from 'date-fns'",
"export const todayISO = () => format(new Date(), 'yyyy-MM-dd')",
"export const fmtDate = iso => { if (!iso) return '—'; try { return format(parseISO(iso), 'd MMM yyyy') } catch { return iso } }",
"export const fmtDateTime = iso => { if (!iso) return '—'; try { return format(parseISO(iso), 'd MMM HH:mm') } catch { return iso } }",
"export const isOverdue = (dueISO, status) => status !== 'Closed' && dueISO && isBefore(parseISO(dueISO), new Date()) && !isToday(parseISO(dueISO))",
"export const doneCt = wo => (wo.wo_tasks || []).filter(t => t.done).length",
"export const spentHrs = wo => (wo.wo_tasks || []).reduce((s, t) => s + (parseFloat(t.hrs_spent) || 0), 0)",
"export function closeBlockers(wo) {",
"  const tasks = wo.wo_tasks || []",
"  if (!tasks.length) return { blocked: false, msgs: [] }",
"  const msgs = []",
"  const unticked = tasks.filter(t => !t.done).length",
"  const noHrs = tasks.filter(t => t.done && (t.hrs_spent == null || isNaN(parseFloat(t.hrs_spent)))).length",
"  if (unticked) msgs.push(unticked + ' task(s) not ticked')",
"  if (noHrs) msgs.push(noHrs + ' ticked task(s) missing hours')",
"  return { blocked: msgs.length > 0, msgs }",
"}",
"export function assetPath(assetId, assets) {",
"  const parts = []",
"  let a = assets.find(x => x.id === assetId)",
"  let guard = 0",
"  while (a && guard++ < 10) { parts.unshift(a.name); a = a.parent_id ? assets.find(x => x.id === a.parent_id) : null }",
"  return parts.join(' › ')",
"}",
"export function buildAssetTree(assets, closedIds = {}) {",
"  const kids = pid => assets.filter(a => (a.parent_id || null) === pid)",
"  const result = []",
"  const walk = (pid, depth) => { kids(pid).forEach(a => { const hasKids = kids(a.id).length > 0; result.push({ a, depth, hasKids }); if (!closedIds[a.id]) walk(a.id, depth + 1) }) }",
"  walk(null, 0)",
"  return result",
"}",
"export const advanceDate = (iso, freq) => { const d = parseISO(iso); if (freq === 'daily') return format(addDays(d,1),'yyyy-MM-dd'); if (freq === 'weekly') return format(addDays(d,7),'yyyy-MM-dd'); return format(addMonths(d,1),'yyyy-MM-dd') }",
"export const PRIORITY_COLOR = { High: '#DC2626', Medium: '#D97706', Low: '#16A34A' }",
"export const KIND_IC = { location: '🏭', line: '🔗', equipment: '🔩', tool: '🧰' }",
].join('\n'))

fs.writeFileSync('src/lib/supabase.js', [
"import { createClient } from '@supabase/supabase-js'",
"const supabaseUrl = import.meta.env.VITE_SUPABASE_URL",
"const supabaseAnon = import.meta.env.VITE_SUPABASE_ANON_KEY",
"export const supabase = createClient(supabaseUrl, supabaseAnon)",
"export async function signOut() { const { error } = await supabase.auth.signOut(); if (error) throw error }",
"export async function fetchProfile(userId) { const { data, error } = await supabase.from('profiles').select('*').eq('id', userId).single(); if (error) throw error; return data }",
"export async function fetchPlantUsers() { const { data, error } = await supabase.from('profiles').select('*').order('name'); if (error) throw error; return data }",
"export async function fetchAssets() { const { data, error } = await supabase.from('assets').select('*').order('name'); if (error) throw error; return data }",
"export async function fetchWorkOrders() {",
"  const { data, error } = await supabase.from('work_orders').select('*, wo_tasks(*), wo_parts(*), wo_log(*)').order('due_date', { ascending: true })",
"  if (error) throw error",
"  return data.map(w => ({ ...w, wo_tasks: (w.wo_tasks||[]).sort((a,b)=>a.position-b.position), wo_log: (w.wo_log||[]).sort((a,b)=>a.created_at<b.created_at?-1:1) }))",
"}",
"export async function createWorkOrder(wo) {",
"  const { tasks, parts, log, ...fields } = wo",
"  const { data, error } = await supabase.from('work_orders').insert(fields).select().single()",
"  if (error) throw error",
"  const woId = data.id",
"  if (tasks && tasks.length) await supabase.from('wo_tasks').insert(tasks.map((t,i)=>({ wo_id:woId, position:i, description:t.description, est_hrs:parseFloat(t.est_hrs)||null })))",
"  if (log && log.length) await supabase.from('wo_log').insert(log.map(l=>({ wo_id:woId, author_name:l.author_name, body:l.body })))",
"  return woId",
"}",
"export async function updateWorkOrder(id, fields) { const { error } = await supabase.from('work_orders').update(fields).eq('id', id); if (error) throw error }",
"export async function updateTask(taskId, fields) { const { error } = await supabase.from('wo_tasks').update(fields).eq('id', taskId); if (error) throw error }",
"export async function addLogEntry(woId, authorId, authorName, body) { const { error } = await supabase.from('wo_log').insert({ wo_id:woId, author_id:authorId, author_name:authorName, body }); if (error) throw error }",
"export async function addPart(woId, name, qty) { const { error } = await supabase.from('wo_parts').insert({ wo_id:woId, name, qty }); if (error) throw error }",
"export async function fetchTaskGroups() { const { data, error } = await supabase.from('task_groups').select('*, task_group_items(*)').order('name'); if (error) throw error; return data.map(g=>({ ...g, task_group_items:(g.task_group_items||[]).sort((a,b)=>a.position-b.position) })) }",
"export async function fetchProjects() { const { data, error } = await supabase.from('projects').select('*').order('created_at',{ascending:false}); if (error) throw error; return data }",
"export async function saveProject(proj) { const { data, error } = await supabase.from('projects').upsert(proj).select().single(); if (error) throw error; return data }",
"export async function fetchSchedules() { const { data, error } = await supabase.from('schedules').select('*').order('next_due'); if (error) throw error; return data }",
"export async function saveSchedule(sched) { const { data, error } = await supabase.from('schedules').upsert(sched).select().single(); if (error) throw error; return data }",
"export async function updateSchedule(id, fields) { const { error } = await supabase.from('schedules').update(fields).eq('id', id); if (error) throw error }",
"export async function deleteSchedule(id) { const { error } = await supabase.from('schedules').delete().eq('id', id); if (error) throw error }",
"export async function fetchWorkRequests() { const { data, error } = await supabase.from('work_requests').select('*, profiles(name,initials,color), assets(name)').order('created_at',{ascending:false}); if (error) throw error; return data }",
"export async function saveWorkRequest(req) { const { data, error } = await supabase.from('work_requests').upsert(req).select().single(); if (error) throw error; return data }",
"export async function fetchPurchaseRequests() { const { data, error } = await supabase.from('purchase_requests').select('*, profiles(name,initials)').order('created_at',{ascending:false}); if (error) throw error; return data }",
"export async function savePurchaseRequest(req) { const { data, error } = await supabase.from('purchase_requests').upsert(req).select().single(); if (error) throw error; return data }",
"export async function fetchUserGroups() { const { data, error } = await supabase.from('user_groups').select('*').order('name'); if (error) throw error; return data }",
"export async function saveUserGroup(group) { const { data, error } = await supabase.from('user_groups').insert(group).select().single(); if (error) throw error; return data }",
"export async function deleteUserGroup(id) { const { error } = await supabase.from('user_groups').delete().eq('id', id); if (error) throw error }",
"export async function upsertAsset(asset) { const { data, error } = await supabase.from('assets').upsert(asset).select().single(); if (error) throw error; return data }",
"export async function createUser(email, password, meta) { const { data, error } = await supabase.auth.signUp({ email, password, options:{ data:meta } }); if (error) throw error; return data }",
].join('\n'))

console.log('Source files written!')